type RouteName =
  | 'adjacent-regions'
  | 'checklist-feed-on-a-date'
  | 'ebird-taxonomy'
  | 'historic-observations-on-a-date'
  | 'hotspot-info'
  | 'hotspots-in-a-region'
  | 'nearby-hotspots'
  | 'nearest-observations-of-a-species'
  | 'recent-checklists-feed'
  | 'recent-nearby-notable-observations'
  | 'recent-nearby-observations'
  | 'recent-nearby-observations-of-a-species'
  | 'recent-notable-observations-in-a-region'
  | 'recent-observations-in-a-region'
  | 'recent-observations-of-a-species-in-a-region'
  | 'region-info'
  | 'regional-statistics-on-a-date'
  | 'species-list-for-a-region'
  | 'sub-region-list'
  | 'taxa-locale-codes'
  | 'taxonomic-forms'
  | 'taxonomic-groups'
  | 'taxonomy-versions'
  | 'top-100'
  | 'view-checklist';

export default RouteName;
